// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SearchProductCode.Data;

#nullable disable

namespace SearchProductCode.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211214113436_IntialCreate")]
    partial class IntialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SearchProductCode.Models.LogoRecip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AMOUNT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LINETYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineProductDef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receipt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogoRecips");
                });
#pragma warning restore 612, 618
        }
    }
}
